### ISSUE TITLE
How to access it?

### ISSUE THREAD

**Issue by hopewise** [corbinu/docker-phpmyadmin#13]
Hello,

I have created a droplet at digitalocean with docker pre-installed at ubuntu 14
now, I have  run the following:

    docker pull corbinu/docker-phpmyadmin
    docker run --name phpmyadmin-mysql -e MYSQL_ROOT_PASSWORD=password -d mysql
    docker run -d --link phpmyadmin-mysql:mysql -e MYSQL_USERNAME=root --name phpmyadmin -p 80 corbinu/docker-phpmyadmin

Shouldn't I be able to view phpmyadmin by viewing the IP address of my server in browser?

**Comment by corbinu** [comment]
Hello,

Did you make sure to run `docker ps` to figure out what port docker mapped to port 80 on the container. If you want the PHPMyAdmin container bound to port 80 you can change the last command to read `-p 80:80` rather then just `-p 80` however if you they try to create another docker container to connect to that mysql DB such as wordpress then you won't be able to also bind it to port 80 on the host. 

Let me know if I can do anything else to help!

**Comment by hopewise** [comment]
Thank you! its the first time to use docker, by using docker ps, I discovered the port number and I now I can access phpmyadmin :)


But how would I access my database using your docker phpmyadmin  image? 
I already know the database name, user name, password, url

Thanks again for your support

**Comment by corbinu** [comment]
No worries always happy to help introduce somebody my startup runs all our services in docker and we love it!

Are you trying to connect to a mysql DB on the host? or on another server rather then the mysql docker container that was started up according to the README?

If so unfortunately although it is possible for an application in a container to access one on the host it is not the ordinary practice and not enabled by default in this container.

So you can either move your data into the MySQL container and then whatever your application is into its own container. The documentation on linking is here: https://docs.docker.com/userguide/dockerlinks/

Otherwise all thought is not the recommended way of doing things you should be able to create your own docker image that uses this as a base and COPY in your own config.inc.php that has the connection information for your DB. 

Let me know if you need help with either possibility

**Comment by corbinu** [comment]
I am going to close the issue as is not an "issue" with the container but feel free to keep asking questions on this issue or send me an email I am happy to help anyway I can

**Comment by hopewise** [comment]
Thanks Corbin! My app is deployed to another server which is provisioned using forge service.
Its hard to move my app to another container, isn't it possible to get a remote mySQL using your container?

**Comment by corbinu** [comment]
Well you could try starting the container like this 

```
docker run -d  -e MYSQL_USERNAME=root -e MYSQL_PORT_3306_TCP_PORT=3306 -e MYSQL_PORT_3306_TCP_ADDR="YOUR REMOTE ADDRESS HERE" --name phpmyadmin -p 80 corbinu/docker-phpmyadmin
```

replacing "YOUR REMOTE ADDRESS HERE" with your remote DB ip.

**Comment by hopewise** [comment]
Thank you
